### PR TITLE
button

### PR DESCRIPTION
**Pull request by raji2004**
## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by raji2004** [comment]
fix issue button on landing page please merge

**Comment by raji2004** [comment]
it said my pr is not accepted is there something wrong with my code?

**Comment by souravcipher** [comment]
Hey @raji2004, added the label. please checkback after sometime. 

Happy hacking!

**Comment by raji2004** [comment]
thanks

**Pull request merged**
