### PR TITLE
Center footer content

### PR DESCRIPTION
**Pull request by zghp**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by zghp** [comment]
[https://github.com/openprivacytech/openprivacytech.org/issues/9](url)

**Comment by souravcipher** [comment]
Hi, thanks for the PR! Closing this as an issue was raised first by someone else.

Please check #3 if you can contribute.

**Comment by zghp** [comment]
Hi, only started working on this because someone else took the issue that I was already working on so I thought first come first served... anyway, I can have a look at 3

**Comment by souravcipher** [comment]
Hey @zghp, going to open this PR again, this issue seems to be hanging for some time. 

Once reviewed It will be merged.

**Review by souravcipher — APPROVED** [review]

**Pull request merged**
